# Generated by Django 5.2 on 2025-04-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uid',
            new_name='uuid',
        ),
    ]
